### ISSUE TITLE
[Codebase]: GitHub workflow to publish tags to NPM

### ISSUE THREAD

**Issue by gremo** [gremo/react-directus#380]
### Description

Right now, new versios are published manually using npm publish command. Maybe a workflow could automate this, when pushing tags. See https://github.com/marketplace/actions/publish-to-npm or try to implement manually using npm commands alone.

### Are you willing to contribute it?

- [ ] I can work on a pull request to implement this improvement

**Comment by Fritsch-Tech** [comment]
I can do this.
All I would need from you is to add the npm token.
> NPM_AUTH_TOKEN: this is the token the action will use to authenticate to [npm](https://npmjs.com/). You need to generate one in npm, then you can add it to your secrets (settings -> secrets) so that it can be passed to the action. DO NOT put the token directly in your workflow file.
